export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const CLEAR_SUCCESS = "CLEAR_SUCCESS";
export const UPDATE_ERROR_MSG = "UPDATE_ERROR_MSG";
export const UPDATE_SUCCESS_MSG = "UPDATE_SUCCESS_MSG";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_SCHOOL_DROPDOWN_REQUIRED = "SET_SCHOOL_DROPDOWN_REQUIRED";
