@startuml Container
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(user, "person", "stuffs")
'  System_Ext(server, "Server")
System_Boundary(c1, "HSPC Website"){
    Container(client, "Client")
    Container(api, "API")
    ContainerDb(database, "Database", "Postgres")

    Rel(user, client, "Uses", "https:")
    Rel(client, api, "Makes api requests to")
    Rel(api, database, "stores and collects values from", "")
}
@enduml