@startuml Context
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(student, "Student", "")
Person(judge, "Judge/Volunteer", "")
Person(master, "Master/Admin", "")
Person(advisor, "Advisor", "")
System(webApp, "HSPC Website", "Website for running the high school programming contest")
' System_Ext(server, "Server", "Optional Description")

Rel(student, webApp, "View the Scoreboard and previous years questions", "https")
Rel(judge, webApp, "Updates scores for teams during the contest", "https")
Rel(master, webApp, "Creates and views users, schools, and events as well as publishes results", "https")
Rel(advisor, webApp, "Manages teams from their school", "https")

'  Rel(server, webApp, "Deploys", "")
@enduml
